<?php

namespace Dmiknys\LaravelModularGenerator\Console\Commands;

use Dmiknys\LaravelModularGenerator\Services\ModularGeneratorCommand;
use Illuminate\Foundation\Console\RequestMakeCommand;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Str;
use Symfony\Component\Console\Input\InputOption;

// TODO: Figure out how to use illuminate/foundation/Console/RequestMakeCommand instead of this
class MakeRequestCommand extends ModularGeneratorCommand
{
    private ?string $makeDto;
    protected $name = 'make:request';
    protected $description = 'Create a new form request class';
    protected $type = 'Request';

    public function handle()
    {
        // TODO: refactor this
        $name = $this->argument('name');
        $nameParts = explode('_', Str::snake($name));

        if (in_array('request', $nameParts, true)) {
            array_pop($nameParts);
            array_push($nameParts, 'dto');

            $dtoName = Str::studly(implode('_', $nameParts));
        } else {
            $dtoName = Str::studly(array_pop($nameParts) . '_dto');
        }

        $this->makeDto = $this->ask('DTO class name?', $dtoName);

        Artisan::call('make:dto', [
            'name' => $dtoName,
            '--module' => $this->option('module'),
            '--force' => $this->option('force'),
        ], $this->output);

        return parent::handle(); // TODO: Change the autogenerated stub
    }

    protected function getStub(): string
    {
        return $this->resolveStubPath('request.stub');
    }

    /**
     * Get the console command arguments.
     *
     * @return array
     */
    protected function getOptions()
    {
        return [
            ['module', 'm', InputOption::VALUE_REQUIRED, 'Create a resource in the specified module'],
            ['force', 'f', InputOption::VALUE_NONE, 'Create the class even if the request already exists'],
        ];
    }

    protected function getEntityNamespace(): string
    {
        return 'Requests';
    }

    protected function buildClass($name): string
    {
        $stub = $this->files->get($this->getStub());

        return $this->replaceNamespace($stub, $name)
            ->replaceDtoImport($stub, config('modular-generator.abstract_request'))
            ->replaceDto($stub, $this->option('module'))
            ->replaceClass($stub, $name);
    }

    private function replaceDtoImport(string &$stub): self
    {
        // TODO: DTOS should be passed dynamically
        $import = $this->getModuledNamespace($this->rootNamespace(), 'Dtos' . '\\' . $this->makeDto);

        $stub = str_replace('{{ DTOImport }}', $import, $stub);

        return $this;
    }

    private function replaceDto(string &$stub, ?string $class): self
    {
        $stub = str_replace('{{ DTO }}', $this->makeDto, $stub);

        return $this;
    }
}